"""empty message

Revision ID: 276672e1ad4f
Revises: 27a36dc4239e
Create Date: 2025-05-09 20:19:25.837354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '276672e1ad4f'
down_revision: Union[str, None] = '27a36dc4239e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('expiration_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('invoice_id', sa.String(length=100), nullable=False),
    sa.Column('invoice_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cities', sa.Column('region_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'cities', 'regions', ['region_id'], ['id'])
    op.add_column('items', sa.Column('production_years', sa.String(), nullable=False))
    op.add_column('items', sa.Column('photo_links', sa.String(), nullable=False))
    op.add_column('items', sa.Column('manufacturer_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'items', 'manufacturers', ['manufacturer_id'], ['id'])
    op.add_column('regions', sa.Column('country_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'regions', 'countries', ['country_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'regions', type_='foreignkey')
    op.drop_column('regions', 'country_id')
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_column('items', 'manufacturer_id')
    op.drop_column('items', 'photo_links')
    op.drop_column('items', 'production_years')
    op.drop_constraint(None, 'cities', type_='foreignkey')
    op.drop_column('cities', 'region_id')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
