"""empty message

Revision ID: 39235afea0f0
Revises: 7d550eda70b1
Create Date: 2025-05-19 18:21:42.610607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39235afea0f0'
down_revision: Union[str, None] = '7d550eda70b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cities', 'region_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('items', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('items', 'photo_links',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'photo_links',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('items', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('cities', 'region_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
