"""empty message

Revision ID: fd6034876c7f
Revises: 
Create Date: 2025-06-07 23:06:22.172956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd6034876c7f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('rp', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('verify_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('token_expires', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_expires')
    op.drop_column('users', 'verify_token')
    op.drop_column('items', 'rp')
    # ### end Alembic commands ###
